cpack_matrix:
  arch:
    - cmake: ci-linux-x64  # selects cmake preset
      rpm: x86_64          # yum $basearch
      deb: amd64           # dpkg --print-architecture
    - cmake: ci-linux-arm
      rpm: armhfp
      deb: armhf
    - cmake: ci-linux-arm64
      rpm: aarch64
      deb: arm64
  distro:
    - name: ubuntu
      version: "22.04"
      release_name: jammy
      type: deb
    - name: ubuntu
      version: "20.04"
      release_name: focal
      type: deb
    - name: ubuntu
      version: "18.04"
      release_name: bionic
      type: deb
    - name: ubuntu
      version: "16.04"
      release_name: xenial
      type: deb
    - name: redhat
      version: "7"
      release_name: ${{ null }}
      type: rpm
      container: docker.io/library/centos:7
    - name: redhat
      version: "8"
      release_name: ${{ null }}
      type: rpm
      container: docker.io/library/rockylinux:8
    - name: redhat
      version: "9"
      release_name: ${{ null }}
      type: rpm
      container: docker.io/library/rockylinux:9
  exclude:
    - distro:
        name: ubuntu
        release_name: xenial
      arch:
        cmake: ci-linux-arm
    - distro:
        name: ubuntu
        release_name: xenial
      arch:
        cmake: ci-linux-arm64
    - distro:
        name: ubuntu
        release_name: bionic
      arch:
        cmake: ci-linux-arm
    - distro:
        name: redhat
      arch:
        cmake: ci-linux-arm
    - distro:
        name: redhat
      arch:
        cmake: ci-linux-arm64
