ARG CMAKE_VERSION="3.22.3"
ARG GITHUB_BASE_URL="https://github.com/"
ARG GITHUB_ORG="openziti"
ARG ZITI_VERSION="0.17.24"
ARG GITHUB_BRANCH="v${ZITI_VERSION}"

FROM quay.io/centos/centos:7

ARG CMAKE_VERSION
ARG GITHUB_BASE_URL
ARG GITHUB_ORG
ARG ZITI_VERSION
ARG GITHUB_BRANCH

USER root
WORKDIR /root/

ENV PATH="/usr/local/:${PATH}"

RUN yum install -y \
        "@Development Tools" \
        centos-release-scl \
        doxygen \
        graphviz \
        python3 \
        systemd-rpm-macros \
        cmake-rpm-macros  \
        zlib-devel && \
    yum install -y \
        devtoolset-10 \
        devtoolset-10-libatomic-devel \
        redhat-lsb && \
    yum clean all

RUN curl -L https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-linux-x86_64.sh -o cmake.sh && \
    (bash cmake.sh --skip-license --prefix=/usr/local) && \
    rm cmake.sh

RUN echo -e "GITHUB_ORG: ${GITHUB_ORG}\nGITHUB_BRANCH: ${GITHUB_BRANCH}"

RUN git clone ${GITHUB_BASE_URL}/${GITHUB_ORG}/ziti-tunnel-sdk-c.git --branch ${GITHUB_BRANCH} --depth 1
    
WORKDIR /root/ziti-tunnel-sdk-c

RUN cmake -E make_directory ./build  
RUN source scl_source enable devtoolset-10 && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./toolchains/default.cmake -S . -B ./build 
RUN source scl_source enable devtoolset-10 && \
    cmake --build ./build --target package --verbose

RUN ./build/programs/ziti-edge-tunnel/ziti-edge-tunnel version